### ISSUE TITLE
ReadMe -error. "dataset/generation_dataset.py"  file not found 

### ISSUE THREAD

**Issue by wangzaistone** [RUCAIBox/LLMBox#249]
Hi, thanks for your great work , a small problem found , that's the link of  "[GenerationDataset](https://github.com/RUCAIBox/LLMBox/tree/main/dataset/generation_dataset.py), [MultipleChoiceDataset](https://github.com/RUCAIBox/LLMBox/tree/main/dataset/multiple_choice_dataset.py)"   in  "https://github.com/RUCAIBox/LLMBox/tree/main/utilization#customize-dataset" readme   shows " file not found " , readme.md need to be update. 

<img width="958" alt="image" src="https://github.com/RUCAIBox/LLMBox/assets/26740509/96bd0a9f-069e-46aa-93c7-edc11b59a28c">

**Comment by huyiwen** [comment]
Those files should be under the utilization folder. Feel free to submit a PR if you would like to help us.
